# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RFjT9Bn_bMPDky7OwW_bxyJeUwOb9wUt

# WEB SCRAPING
"""

import requests
from bs4 import BeautifulSoup

request =requests.get("https://wuzzuf.net/search/jobs/?a=hpb&q=&start=0")
request

request.content

soup=BeautifulSoup(request.content,"html.parser")

soup

jops=soup.find_all("div",class_="css-1gatmva e1v1l3u10")
len(jops)

jops[0]

job_name=jops[0].find_all("h2",class_="css-m604qf")[0].text
# jops[1].find_all("h2",class_="css-m604qf")[0].text
job_name
# len(jops[0].find_all("h2",class_="css-m604qf"))

# company_name=jops[0].find_all("div",class_="css-d7j1kk")[0].text.split(",")[0]
company_name=jops[1].find_all("div",class_="css-d7j1kk")[0].text.split(",")[0].split("-") [0]
company_name

# location_name=jops[1].find_all("div",class_="css-d7j1kk")[0].text.split(",")[0].split("-") [1]
# location_name
# or
location_name=jops[1].find_all("span",class_="css-5wys0k")[0].text.split(",")[0]
location_name

natural=jops[13].find_all("div",class_="css-1lh32fc")[0].text
natural

exp_level=jops[3].find_all("div",class_="css-1lh32fc")[0].next_sibling.text ## جينا الى قبلها وبعدين جتبنا next_sibling ده كله عشان مفيش محتوى فى div
exp_level.split("·")[0]

Yrs_of_Exp=jops[3].find_all("div",class_="css-1lh32fc")[0].next_sibling.text ## جينا الى قبلها وبعدين جتبنا next_sibling ده كله عشان مفيش محتوى فى div
Yrs_of_Exp.split("·")[1]

skills=jops[1].find_all("div",class_="css-1lh32fc")[0].next_sibling.text ## جينا الى قبلها وبعدين جتبنا next_sibling ده كله عشان مفيش محتوى فى div
" ".join(skills.split("·")[2:])

import pandas as pd
df=pd.DataFrame(columns=["job_name","company_name","location","job_type","exp_level","exp_years"])

df

# df.loc[len(df.index)]=["data sci","et","cairo","senior","1","python"]

# df

df

for job in jops:
    job_name = job.find_all("h2", class_ = "css-m604qf")[0].text
    company_name = job.find_all("div", class_ = "css-d7j1kk")[0].text.split(" - ")[0]
    location = job.find_all("span", class_ = "css-5wys0k")[0].text.split(", ")[0]
    job_type = job.find_all("span", class_ = "css-1ve4b75 eoyjyou0")[0].text
    exp_level = job.find_all("div", class_ = "css-1lh32fc")[0].next_sibling.text.split(" · ")[0]
    exp_years = job.find_all("div", class_ = "css-1lh32fc")[0].next_sibling.text.split(" · ")[1]

    df.loc[len(df.index)] = [job_name, company_name, location, job_type, exp_level, exp_years]

df

import requests
from bs4 import BeautifulSoup
import pandas as pd
df=pd.DataFrame(columns=["Job Name", "Company Name", "Location", "Job Type", "Experience Level", "Experience Years"])
for i in range(534):
    request = requests.get(f"https://wuzzuf.net/search/jobs/?a=hpb&q=&start={i}")
    content = request.content
    soup = BeautifulSoup(content, "html.parser")
    jobs = soup.find_all("div", class_ = "css-1gatmva e1v1l3u10")

    for job in jobs:
        job_name = job.find_all("h2", class_ = "css-m604qf")[0].text
        company_name = job.find_all("div", class_ = "css-d7j1kk")[0].text.split(" - ")[0]
        location = job.find_all("span", class_ = "css-5wys0k")[0].text.split(", ")[0]
        job_type = job.find_all("span", class_ = "css-1ve4b75 eoyjyou0")[0].text
        exp_level = job.find_all("div", class_ = "css-1lh32fc")[0].next_sibling.text.split(" · ")[0]
        exp_years = job.find_all("div", class_ = "css-1lh32fc")[0].next_sibling.text.split(" · ")[1]

        df.loc[len(df.index)] = [job_name, company_name, location, job_type, exp_level, exp_years]
    if i % 50==0:
      print ("Done")

df























